# Generated by Django 3.0.7 on 2020-06-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffDetails',
            fields=[
                ('staffId', models.TextField(primary_key=True, serialize=False)),
                ('subName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='subjectTable',
            fields=[
                ('subCode', models.TextField(primary_key=True, serialize=False)),
                ('subName', models.TextField()),
                ('semester', models.IntegerField()),
                ('isLab', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='staffTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
                ('period', models.IntegerField()),
                ('classId', models.TextField()),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.staffDetails')),
                ('subCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subjectTable')),
            ],
        ),
        migrations.CreateModel(
            name='classTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField()),
                ('period', models.IntegerField()),
                ('classId', models.TextField()),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.staffDetails')),
                ('subCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subjectTable')),
            ],
        ),
    ]
